import { IPromptBuilder, IPromptContext } from '../types/aiIntegration';

/**
 * Pure deterministic Prompt Builder Engine.
 * Formats high-context analytical primitives from PR4.4 and PR4.7 
 * into an optimized markdown prompt layout for external LLM parsing.
 */
export class PromptBuilder implements IPromptBuilder {
  /**
   * Transforms structured intelligence summaries into a highly targeted instruction prompt.
   * Eliminates system variance and preserves deterministic data structures.
   */
  public buildPrompt(context: IPromptContext): string {
    const { recommendationPayload, reportPayload, timestamp } = context;

    const formattedDate = new Date(timestamp).toISOString();
    
    // Extract Recommendation Layer Details safely
    const primaryCode = recommendationPayload?.primaryActionCode || 'REC_NONE';
    const recsList = Array.isArray(recommendationPayload?.recommendations) 
      ? recommendationPayload.recommendations.map((r: any) => `- [${r.priority}] ${r.actionItem}: ${r.rationale}`).join('\n')
      : '- No active engine recommendations available.';

    // Extract Report Layer Details safely
    const reportType = reportPayload?.type || 'UNKNOWN';
    const evaluatedPoints = reportPayload?.dataPointsEvaluated || 0;
    const alertCount = reportPayload?.criticalAlertCount || 0;
    
    const hr = reportPayload?.metrics?.heartRate || { min: 0, max: 0, average: 0 };
    const spo2 = reportPayload?.metrics?.spo2 || { min: 0, max: 0, average: 0 };
    const gas = reportPayload?.metrics?.gas || { min: 0, max: 0, average: 0 };

    const scores = reportPayload?.healthScores || { cardiovascularScore: 0, respiratoryScore: 0, environmentalSafetyScore: 0, overallHealthScore: 0 };
    const directives = Array.isArray(reportPayload?.primaryRiskDirectives)
      ? reportPayload.primaryRiskDirectives.map((d: string) => `- ${d}`).join('\n')
      : '- No strategic directives specified.';

    // Build standard high-context instruction payload string
    return `[SYSTEM INSTRUCTION: ANALYZE HEALTH INSIGHTS PAYLOAD]
You are acting as an expert physiological analytics optimization assistant. Below is the deterministic health intelligence snapshot generated by the NOEXCUSE HPO V2 pipeline. Review the structured telemetry conclusions, metrics aggregations, and strategic safety protocols to provide a contextual performance analysis and optimization recommendation report.

### System Metadata
- Snapshot Timestamp: ${formattedDate}
- Report Context Scope: ${reportType}

### 1. Active Engine Recommendations (PR4.4)
- Primary Action Trigger Code: ${primaryCode}
Active Directives:
${recsList}

### 2. Aggregated Long-Term Metrics (PR4.7)
- Aggregation Window Size: ${evaluatedPoints} data periods
- Total Critical Alerts: ${alertCount}

Aggregated Telemetry Frames:
* Heart Rate: Min ${hr.min} bpm | Max ${hr.max} bpm | Avg ${hr.average} bpm
* SpO2 Saturation: Min ${hr.min === 0 ? 0 : spo2.min}% | Max ${spo2.max}% | Avg ${spo2.average}%
* Environmental Gas: Min ${gas.min} ppm | Max ${gas.max} ppm | Avg ${gas.average} ppm

### 3. Analytics System Health Scores
* Cardiovascular Subscore: ${scores.cardiovascularScore}/100
* Respiratory Subscore: ${scores.respiratoryScore}/100
* Environmental Safety Subscore: ${scores.environmentalSafetyScore}/100
* Overall Composite Health Score: ${scores.overallHealthScore}/100

### 4. Strategic Risk Management Framework Directives
${directives}

[ANALYSIS OBJECTIVE]
Synthesize these parameters to deliver actionable optimization adjustments for physical preparation, outlining how the trends correlate to environmental parameters and systemic load, without altering the baseline thresholds.`;
  }
}\n