/**
 * PR8.7: AI Safety and Guardrails Service
 * Enforces safety boundaries, medical disclaimers, and emergency escalation checks.
 */

import { StructuredHealthInterpretation, InterpretationRiskLevel } from "../types/aiContracts";

export class AISafetyGatekeeper {
    private readonly mandatoryDisclaimer =
        "DISCLAIMER: This analysis is generated by an AI assistant for informational purposes only. " +
        "It does not constitute medical advice, diagnosis, or treatment. Always consult a qualified physician for clinical concerns.";

    private readonly emergencyKeywords = [
        "chest pain", "shortness of breath", "severe hypoxia",
        "cardiac arrest", "arrhythmia alert", "critical drop"
    ];

    /**
     * Applies safety filters, emergency checks, and disclaimers to health interpretations
     */
    public applySafetyGuardrails(
        interpretation: StructuredHealthInterpretation
    ): StructuredHealthInterpretation {
        const sanitized = { ...interpretation };

        // 1. Mandatory Disclaimer Injection
        sanitized.disclaimer = this.mandatoryDisclaimer;

        // 2. Emergency Escalation Detection
        const lowerSummary = sanitized.summary.toLowerCase();
        const isEmergencyTriggered = this.emergencyKeywords.some(kw => lowerSummary.includes(kw));

        if (isEmergencyTriggered) {
            sanitized.riskLevel = "CRITICAL";
            sanitized.recommendations.unshift({
                id: "REC_EMERGENCY_01",
                actionItem: "Seek immediate emergency medical care or call local emergency services.",
                priority: "IMMEDIATE",
                rationale: "Critical physiological parameters or severe symptom triggers detected in health telemetry."
            });
        }

        // 3. Phrase Sanitization (Preventing diagnostic assertions)
        sanitized.summary = this.sanitizeDiagnosticPhrasing(sanitized.summary);

        return sanitized;
    }

    private sanitizeDiagnosticPhrasing(text: string): string {
        return text
            .replace(/you have/gi, "telemetry indicates patterns consistent with")
            .replace(/you are suffering from/gi, "data shows potential indicators of");
    }
}
